# SQL Query
"""
SELECT SUM(case when Instrument IS NOT NULL then 1 end) as Instrument,
SUM(case when Book_Value_Per_Share IS NOT NULL then 1 end) as Book_Value_Per_Share,
SUM(case when Cash_and_Short_Term_Investments IS NOT NULL then 1 end) as Cash_and_Short_Term_Investments,
SUM(case when Cost_of_Revenue__Total IS NOT NULL then 1 end) as Cost_of_Revenue__Total,
SUM(case when Current_Ratio IS NOT NULL then 1 end) as Current_Ratio,
SUM(case when Diluted_EPS_Excluding_Extraordinary_Items IS NOT NULL then 1 end) as Diluted_EPS_Excluding_Extraordinary_Items,
SUM(case when Diluted_EPS_Including_Extraordinary_Items IS NOT NULL then 1 end) as Diluted_EPS_Including_Extraordinary_Items,
SUM(case when EBIT IS NOT NULL then 1 end) as EBIT,
SUM(case when EBIT_Margin__Percent IS NOT NULL then 1 end) as EBIT_Margin__Percent,
SUM(case when Goodwill__Net IS NOT NULL then 1 end) as Goodwill__Net,
SUM(case when Gross_Dividends___Common_Stock IS NOT NULL then 1 end) as Gross_Dividends___Common_Stock,
SUM(case when Gross_Margin__Percent IS NOT NULL then 1 end) as Gross_Margin__Percent,
SUM(case when Net_Income_Before_Taxes IS NOT NULL then 1 end) as Net_Income_Before_Taxes,
SUM(case when Normalized_Income_Avail_to_Cmn_Shareholders IS NOT NULL then 1 end) as Normalized_Income_Avail_to_Cmn_Shareholders,
SUM(case when Operating_Expenses IS NOT NULL then 1 end) as Operating_Expenses,
SUM(case when Operating_Income IS NOT NULL then 1 end) as Operating_Income,
SUM(case when Operating_Margin__Percent IS NOT NULL then 1 end) as Operating_Margin__Percent,
SUM(case when Property_Plant_Equipment__Total___Net IS NOT NULL then 1 end) as Property_Plant_Equipment__Total___Net,
SUM(case when Quick_Ratio IS NOT NULL then 1 end) as Quick_Ratio,
SUM(case when ROA_Total_Assets__Percent IS NOT NULL then 1 end) as ROA_Total_Assets__Percent,
SUM(case when Revenue_Per_Share IS NOT NULL then 1 end) as Revenue_Per_Share,
SUM(case when Date IS NOT NULL then 1 end) as Date,
SUM(case when Tangible_Book_Value_Per_Share IS NOT NULL then 1 end) as Tangible_Book_Value_Per_Share,
SUM(case when Total_Assets__Reported IS NOT NULL then 1 end) as Total_Assets__Reported,
SUM(case when Total_Current_Liabilities IS NOT NULL then 1 end) as Total_Current_Liabilities,
SUM(case when Total_Current_Assets IS NOT NULL then 1 end) as Total_Current_Assets,
SUM(case when Total_Debt IS NOT NULL then 1 end) as Total_Debt,
SUM(case when Total_Equity IS NOT NULL then 1 end) as Total_Equity,
SUM(case when Total_Inventory IS NOT NULL then 1 end) as Total_Inventory,
SUM(case when Total_Liabilities IS NOT NULL then 1 end) as Total_Liabilities,
SUM(case when Total_Long_Term_Debt IS NOT NULL then 1 end) as Total_Long_Term_Debt,
SUM(case when Total_Receivables__Net IS NOT NULL then 1 end) as Total_Receivables__Net,
SUM(case when Total_Revenue IS NOT NULL then 1 end) as Total_Revenue,
SUM(case when Total_Common_Shares_Outstanding IS NOT NULL then 1 end) as Total_Common_Shares_Outstanding,
SUM(case when Total_Debt_to_Total_Equity__Percent IS NOT NULL then 1 end) as Total_Debt_to_Total_Equity__Percent,
SUM(case when Company_Common_Name IS NOT NULL then 1 end) as Company_Common_Name,
SUM(case when Exchange_Name IS NOT NULL then 1 end) as Exchange_Name,
SUM(case when Country_of_Headquarters IS NOT NULL then 1 end) as Country_of_Headquarters,
SUM(case when TRBC_Economic_Sector_Name IS NOT NULL then 1 end) as TRBC_Economic_Sector_Name,
SUM(case when Has_Div IS NOT NULL then 1 end) as Has_Div
FROM seng_550_data.fundamentals
"""

amount_of_nulls = {
    "Instrument": None,
    "Book_Value_Per_Share": "13298",
    "Cash_and_Short_Term_Investments": "45573",
    "Cost_of_Revenue__Total": "62124",
    "Current_Ratio": "56408",
    "Diluted_EPS_Excluding_Extraordinary_Items": "5395",
    "Diluted_EPS_Including_Extraordinary_Items": "5298",
    "EBIT": "3304",
    "EBIT_Margin__Percent": "16558",
    "Goodwill__Net": "106602",
    "Gross_Dividends___Common_Stock": None,
    "Gross_Margin__Percent": "64942",
    "Net_Income_Before_Taxes": "4604",
    "Normalized_Income_Avail_to_Cmn_Shareholders": "4844",
    "Operating_Expenses": "3330",
    "Operating_Income": "34613",
    "Operating_Margin__Percent": "51219",
    "Property_Plant_Equipment__Total___Net": "21672",
    "Quick_Ratio": "56408",
    "ROA_Total_Assets__Percent": "16511",
    "Revenue_Per_Share": "3707",
    "Date": "461",
    "Tangible_Book_Value_Per_Share": "12717",
    "Total_Assets__Reported": "12465",
    "Total_Current_Liabilities": "56310",
    "Total_Current_Assets": "56268",
    "Total_Debt": "12768",
    "Total_Equity": "12440",
    "Total_Inventory": "103296",
    "Total_Liabilities": "12592",
    "Total_Long_Term_Debt": "12966",
    "Total_Receivables__Net": "55761",
    "Total_Revenue": "34292",
    "Total_Common_Shares_Outstanding": "12789",
    "Total_Debt_to_Total_Equity__Percent": "22175",
    "Company_Common_Name": None,
    "Exchange_Name": "1129",
    "Country_of_Headquarters": None,
    "TRBC_Economic_Sector_Name": "238",
    "Has_Div": None}

amount_of_not_nulls = {
    "Instrument": "195636",
    "Book_Value_Per_Share": "182338",
    "Cash_and_Short_Term_Investments": "150063",
    "Cost_of_Revenue__Total": "133512",
    "Current_Ratio": "139228",
    "Diluted_EPS_Excluding_Extraordinary_Items": "190241",
    "Diluted_EPS_Including_Extraordinary_Items": "190338",
    "EBIT": "192332",
    "EBIT_Margin__Percent": "179078",
    "Goodwill__Net": "89034",
    "Gross_Dividends___Common_Stock": "195636",
    "Gross_Margin__Percent": "130694",
    "Net_Income_Before_Taxes": "191032",
    "Normalized_Income_Avail_to_Cmn_Shareholders": "190792",
    "Operating_Expenses": "192306",
    "Operating_Income": "161023",
    "Operating_Margin__Percent": "144417",
    "Property_Plant_Equipment__Total___Net": "173964",
    "Quick_Ratio": "139228",
    "ROA_Total_Assets__Percent": "179125",
    "Revenue_Per_Share": "191929",
    "Date": "195175",
    "Tangible_Book_Value_Per_Share": "182919",
    "Total_Assets__Reported": "183171",
    "Total_Current_Liabilities": "139326",
    "Total_Current_Assets": "139368",
    "Total_Debt": "182868",
    "Total_Equity": "183196",
    "Total_Inventory": "92340",
    "Total_Liabilities": "183044",
    "Total_Long_Term_Debt": "182670",
    "Total_Receivables__Net": "139875",
    "Total_Revenue": "161344",
    "Total_Common_Shares_Outstanding": "182847",
    "Total_Debt_to_Total_Equity__Percent": "173461",
    "Company_Common_Name": "195636",
    "Exchange_Name": "194507",
    "Country_of_Headquarters": "195636",
    "TRBC_Economic_Sector_Name": "195398",
    "Has_Div": "195636"}


for key in amount_of_not_nulls.keys():
    not_nulls_count = amount_of_not_nulls[key]
    nulls_count = amount_of_nulls[key]

    if nulls_count is None:
        nulls_count = 0

    not_nulls_count = int(not_nulls_count)
    nulls_count = int(nulls_count)

    total = not_nulls_count + nulls_count

    print("{} is {:.2f}% nulls".format(key, (nulls_count/total)* 100))
